### ISSUE TITLE
ReadTheDocs

### ISSUE THREAD

**Issue by kbarnhart** [TerrainBento/terrainbento#2]
Need to successfully build on readthedocs, 

and need to learn how to change the names to be not the defaults.

**Comment by kbarnhart** [comment]
Regarding the first issue, this has been a total drag. 

I get import issues regarding yaml not being found even after yaml has been installed. @mcflugen recommended that I use mock packages in sphinx. but my issue predates even using sphinx in the readthedocs workflow. 

```
python /home/docs/checkouts/readthedocs.org/user_builds/terrainbento/envs/latest/bin/pip install --use-wheel --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/terrainbento/.cache/pip -I Pygments==2.2.0 setuptools==37.0.0 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.6.5 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6
```

fails with 

```Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from -r /home/docs/checkouts/readthedocs.org/user_builds/terrainbento/checkouts/latest/requirements.txt (line 1))
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from -r /home/docs/checkouts/readthedocs.org/user_builds/terrainbento/checkouts/latest/requirements.txt (line 2))
Collecting dill (from -r /home/docs/checkouts/readthedocs.org/user_builds/terrainbento/checkouts/latest/requirements.txt (line 3))
  Downloading dill-0.2.7.1.tar.gz (64kB)
Collecting landlab (from -r /home/docs/checkouts/readthedocs.org/user_builds/terrainbento/checkouts/latest/requirements.txt (line 4))
  Using cached landlab-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j4xvjr27/landlab/setup.py", line 73, in <module>
        from landlab import __version__
      File "/tmp/pip-build-j4xvjr27/landlab/landlab/__init__.py", line 27, in <module>
        from .core.model_parameter_dictionary import ModelParameterDictionary
      File "/tmp/pip-build-j4xvjr27/landlab/landlab/core/__init__.py", line 1, in <module>
        from .model_parameter_loader import load_params
      File "/tmp/pip-build-j4xvjr27/landlab/landlab/core/model_parameter_loader.py", line 5, in <module>
        import yaml
    ImportError: No module named 'yaml'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j4xvjr27/landlab/
```

using a dummy requirements.txt file requirements_read_the_docs.txt that only has numpy and scipy in it gets us one step further to attempting to run ```python setup.py install --force``` but this only works when  install_requires in the setup.py file is removed. 

I also tried modifying the requirements_read_the_docs.txt file  

```
numpy
scipy
landlab --install-option="--no-deps" \
    --install-option="--no-compile"
```
this also doesn't work. 

when we move past the `setup.py` step, I get an error on the next step. 

```
python /home/docs/checkouts/readthedocs.org/user_builds/terrainbento/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```
errors with 

```
Running Sphinx v1.6.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/terrainbento/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/terrainbento/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/terrainbento/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/terrainbento/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 22, in <module>
    import terrainbento
  File "/home/docs/checkouts/readthedocs.org/user_builds/terrainbento/envs/latest/lib/python3.5/site-packages/terrainbento-0+untagged.48.g3b6fbd4-py3.5.egg/terrainbento/__init__.py", line 10, in <module>
    from .base_class import ErosionModel
ImportError: No module named 'terrainbento.base_class'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/terrainbento/envs/latest/lib/python3.5/site-packages/terrainbento-0+untagged.48.g3b6fbd4-py3.5.egg/terrainbento/__init__.py", line 10, in <module>
    from .base_class import ErosionModel
ImportError: No module named 'terrainbento.base_class'
The full traceback has been saved in /tmp/sphinx-err-f7zapb0y.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

To address this I updated the setup.py file to use packages=find_packages()

Then I got another landlab import error from 

```
 from landlab.io import read_esri_ascii
ImportError: No module named 'landlab'
```

I would have thought that this was dealt with by my command 

```
autodoc_mock_imports = ['landlab', 'dill', 'numpy', 'scipy', 'yaml']
```

But no dice, the issue seems to be that in order to import terrainbento I need to import landlab, and that is not mocked. 

I then tried mocking the dependency modules BEFORE importing terrainbento. 
```python
import os
import sys


from unittest.mock import MagicMock
autodoc_mock_imports = ['landlab', 'dill', 'numpy', 'scipy', 'yaml']
for mod_name in autodoc_mock_imports:
    sys.modules[mod_name] = MagicMock()

import terrainbento
```
still no dice.

**Comment by kbarnhart** [comment]
https://stackoverflow.com/questions/23900878/python-mock-a-module 
might help

**Comment by kbarnhart** [comment]
PRs #4 and #5 fixed the doc building (thanks @mcflugen !!!!!!)

PRs #9 #10 #11 dealt with getting the structure correct. closing.
